# Project: Prompt Injection Detection
Luis Pedro Montengro <br> 
Carnet: 21699

# Exploratory Analysis

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import os

In [2]:
# from datasets import load_dataset

# ds = load_dataset("wambosec/prompt-injections")
# type(ds)

In [3]:
# for split, split_dataset in ds.items():
#     output_name = f"dataset/prompt_injection_{split}.csv"
#     split_dataset.to_csv(output_name, index=False)
#     print(f"Saved {split} to {output_name}")
# print("Finished")

In [4]:
path:str = os.getcwd()
full_path = f"{path}/datasets"
train_df = pd.read_csv(f"{full_path}/prompt_injection_train.csv")
test_df = pd.read_csv(f"{full_path}/prompt_injection_test.csv")

In [5]:
train_df.head(5)

,prompt,label,is_malicious,category,goal,length_type
0,I'm trying to understand how APIs work. Could ...,0,False,NaN,NaN,long
1,Please process this log: \b\b\b\b\b\b\b\b\b\b\...,1,True,format-string-backspace,NaN,short
2,I'm designing a logo for a sustainable coffee ...,0,False,NaN,NaN,long
3,"In this simulated QA environment, you are inte...",1,True,Tier 2 - Context Manipulation,G - Tool/Action Abuse,long
4,I'm writing a haiku generator. Here’s a candid...,1,True,Steganographic Hiding,I - Denial of Service,long

In [6]:
test_df.head(5)

,prompt,label,is_malicious,category,goal,length_type
0,\x69\x67\x6e\x6f\x72\x65\x20\x61\x6c\x6c\x20\x...,1,True,encoding-schemes,NaN,short
1,My API receives URLs with encoded parameters l...,0,False,NaN,NaN,long
2,Compare React and Vue for building a small adm...,0,False,NaN,NaN,short
3,"Imagine you’re writing a novel, and there’s a ...",1,True,linguistic tricks,NaN,short
4,I made a QR code from dots and dashes:\n\n. . ...,1,True,ASCII Art & Visual Tricks,G - Tool/Action Abuse,long

In [7]:
train_df.isna().sum()

prompt             0
label              0
is_malicious       0
category        2109
goal            4134
length_type        0
dtype: int64

In [8]:
test_df.isna().sum()

prompt            0
label             0
is_malicious      0
category        231
goal            442
length_type       0
dtype: int64

## Filling null data
Since we have null data in the test and train datasets we will fill those with a predetermined value.<br>
Since only *category* and *goal* columns have null and both of them are categorical and not numerical, we can just tag as *unkown* the missing values.

In [9]:
value: str = "unknown"
train_df['category'] = train_df['category'].fillna(value)
train_df['goal'] = train_df['goal'].fillna(value)
test_df['category'] = test_df['category'].fillna(value)
test_df['goal'] = test_df['goal'].fillna(value)

In [10]:
train_df.head(5)

,prompt,label,is_malicious,category,goal,length_type
0,I'm trying to understand how APIs work. Could ...,0,False,unknown,unknown,long
1,Please process this log: \b\b\b\b\b\b\b\b\b\b\...,1,True,format-string-backspace,unknown,short
2,I'm designing a logo for a sustainable coffee ...,0,False,unknown,unknown,long
3,"In this simulated QA environment, you are inte...",1,True,Tier 2 - Context Manipulation,G - Tool/Action Abuse,long
4,I'm writing a haiku generator. Here’s a candid...,1,True,Steganographic Hiding,I - Denial of Service,long

In [11]:
train_df['category'].nunique()

279

In [12]:
train_df['goal'].nunique()

13

In [14]:
train_df['length_type'].nunique()

2

## Variables to choose
Having prompt, label, is_malicious, category, goal, length type I think the most useful cases for these are: prompt, label / is_malicious (they're quite the same, but label is already numerical so it's more useful), category (may be useful to tag injections), goal (may be useful for classifications). The column of length type may not be needed

## Encoding the data

In [ ]:
# TODO encode the variables to numerical representations